# Generated by Django 6.0.3 on 2026-03-17 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, verbose_name='Marke')),
                ('model', models.CharField(max_length=100, verbose_name='Modelis')),
                ('license_plate', models.CharField(max_length=50, unique=True, verbose_name='Valstybinis nr.')),
                ('vin_code', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='Kebulo numeris')),
                ('client_name', models.CharField(max_length=150, verbose_name='Klijentas')),
            ],
            options={
                'verbose_name': 'Automobilis',
                'verbose_name_plural': 'Automobiliai',
                'ordering': ['license_plate'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Paslaugos pavadinimas')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Kaina (€)')),
            ],
            options={
                'verbose_name': 'Paslauga',
                'verbose_name_plural': 'Paslaugos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Uzsakymo data ir laikas')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservice.car', verbose_name='Automobilis')),
            ],
            options={
                'verbose_name': 'Uzsakymas',
                'verbose_name_plural': 'Uzsakymai',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Kiekis')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='autoservice.order', verbose_name='Uzsakymas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autoservice.service', verbose_name='Paslauga')),
            ],
            options={
                'verbose_name': 'Usakymo eile',
                'verbose_name_plural': 'Uzsakymo eiles',
            },
        ),
    ]
