# Generated by Django 6.0.3 on 2026-03-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_line',
            new_name='OrderLine',
        ),
    ]
