# Generated by Django 6.0.3 on 2026-03-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_rename_order_line_orderline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Usakymo eilute', 'verbose_name_plural': 'Uzsakymo eilutes'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Naujas'), ('in_progress', 'Vykdomas'), ('done', 'Baigtas'), ('cancelled', 'Atsauktas'), ('waiting', 'Laukiantis')], default='new', max_length=20, verbose_name='Uzsakymo busena'),
        ),
    ]
